<link rel="stylesheet" href="css/style.css">
<main class="text-center">
    <form action="admin.php" method="POST">
        <h1>Connexion</h1>
        <div>
            <label for="inputuser" class="sr-only"></label>
            <input name="user" type="user" id="user" class="form-control" placeholder="Username" required autofocus>
       </div>
       <div>
            <label for="inputPassword" class="sr-only"></label>
            <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
       </div>
        <div class="remember">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="boutons" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
</main>
