<main role="main">
    <div class="container">
        <form method="POST">
            <div class="entreprise"><br><br><br><br>
                <h2>Ajouter une offre</h2><br>
                <div class="form-group">
                    <input name="title" type="product" class="form-control" placeholder="Titre de l'Offre">
                </div>
                <div class="element">
                    <input name="type" type="product" class="form-control" placeholder="Type de Contrat (Stage / Alternance / CDD / CDI)">
                </div><br>
                <div class="element">
                    <input name="formation" type="product" class="form-control" placeholder="Formation (Ynov Informatique / Ynov Digital Business School / Ynov Web, Com & Graphic Design / Ynov Audiovisuel / Ynov Animation 3D Jeux Vidéo)">
                </div><br>
                <div class="element">
                    <input name="class" type="product" class="form-control" placeholder="Promotion (B1 / B2 / B3 / M1 / M2)">
                </div><br>
                <textarea name="description" class="form-control" placeholder="Description"></textarea><br>
                <div class="element">
                    <input name="period" type="product" class="form-control" placeholder="Durée du Contrat">
                </div>
            </div>
            <br><button type="submit" class="btn btn-primary">Ajouter</button><br><br>
        </form>
    </div>
</main>
