<main role="main">
    <div class="container">
        <form method="POST">
            <div>
                <h2>L'entreprise</h2><br>
                <div class="form-group">
                    <input type="email" class="form-control" id="exampleInputPassword1" placeholder="Email">
                </div>
                <div class="form-group">
                    <input type="Nom de l'entreprise" class="form-control" id="exampleInputPassword1" placeholder="Nom de l'entreprise">
                </div>
                <div class="form-group">
                    <input type="tel" class="form-control" id="exampleInputPassword1" placeholder="Téléphone">
                </div>
            </div>
            <textarea name="text" class="form-control" placeholder="Text"></textarea><br><br>
            <div>
                <h2>L'étudiant recherché</h2><br>
                <div class="form-group">
                    <select id="disabledSelect" class="form-control">
                        <option>Année d'etude</option>
                        <option>Bachelor Première année</option>
                        <option>Bachelor Deuxième année</option>
                        <option>Bachelor Troisième année</option>
                        <option>Master Première année</option>
                        <option>Master Deuxième année</option>
                    </select>
                </div>
                <div class="form-group">
                    <select id="disabledSelect" class="form-control">
                        <option>Formation</option>
                        <option>Ynov Informatique</option>
                        <option>Ynov Digital Business School</option>
                        <option>Ynov Web, Com & Graphic Design</option>
                        <option>Ynov Audiovisuel</option>
                        <option>Ynov Animation 3D Jeux Vidéo</option>
                    </select>
                </div>
                <div class="form-group">
                    <select id="disabledSelect" class="form-control">
                        <option>Type de contrat recherché</option>
                        <option>Stage</option>
                        <option>Alternance</option>
                        <option>CDI</option>
                        <option>CDD</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="Spécialité" class="form-control" id="exampleInputPassword1" placeholder="Spécialité">
                </div><br>
            </div>
            <div class="g-recaptcha" data-sitekey="6Le761sUAAAAADdW7U433MfpXaToOjzfpfEvm1jX"></div>
            <br><button type="submit" class="btn btn-primary">Envoyer</button><br><br>
        </form>
    </div>
</main>
